Fix cloud config schema error
Recent versions of cloud-init show the following warning:

    network-config-v1 failed schema validation! You may run 'sudo cloud-init schema --system' to check the details.

This is because the mtu value is a string instead of an integer:

    Error: Cloud config schema errors: config.0.mtu: '1442' is not of type 'integer', 'null'